config/routes.rb
Rails.application.routes.draw do
  concern :snake do
    get '/', to: 'snake#root', as: nil
    post '/start',  to: 'snake#start',  as: nil
    post '/move',  to: 'snake#move',  as: nil
    post '/end',   to: 'snake#end',   as: nil
  end

  concerns :snake

  scope "/ml", default: { ml: true } do
    concerns :snake
  end

  resources :games, only: [:index, :show]
  resources :moves, only: [:show]
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def show
    @move = Storage::Move.find(params[:id])
    @game = @move.game

    @simulate_game = ::Game.from_json(@move.state)
    @move_decider = MoveDecider.new(@simulate_game, scorer: @game.default_scorer)
    @simulated_move = @move_decider.next_move
  end
end

app/views/moves/show.html.erb
<dl>
  <dt>Game</dt>
  <dd><%= link_to @game.external_id, game_path(@game) %></dd>
  <dt>Time</dt>
  <dd><%= l @move.created_at %></dd>
  <dt>Runtime</dt>
  <dd><%= number_with_precision(@move.runtime * 1000, precision: 1) %> ms</dd>
  <dt>Snake version</dt>
  <dd><%= version_link @game.snake_version %></dd>
  <dt>Decision</dt>
  <dd>
    <% if @simulated_move.to_s == @move.decision.to_s %>
      <%= @move.decision %>
    <% else %>
      was <%= @move.decision %>, would now be <%= @simulated_move %>
    <% end %>
  </dd>
</dl>

<%= link_to "< prev", move_path(@move.prev) if @move.prev %>
<%= link_to "next >", move_path(@move.next) if @move.next %>

<table>
  <thead>
    <tr>
      <th>Before</th>
      <th>After</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= image_tag @move.before_image_url %>
      </td>
      <td>
        <%= image_tag @move.after_image_url %>
      </td>
    </tr>
    <tr>
      <td>
        <%= @move.heuristic_score %>
      </td>
      <td>
        <%= @move.next&.heuristic_score %>
      </td>
    </tr>
  </tbody>
<table>

<table class="table">
  <thead>
    <tr>
      <th>Moves</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <% @move.move_decider.possible_futures.each do |future| %>
      <tr>
        <td>
          <%= content_tag :pre, future.moves_by_name.to_yaml.sub("---\n", "") %>
        </td>
        <td>
          <%= future.score %>
        </td>
      </tr>
    <% end %>
  </tbody>
<table>