config/routes.rb
Rails.application.routes.draw do
  concern :snake do
    get '/', to: 'snake#root', as: nil
    post '/start',  to: 'snake#start',  as: nil
    post '/move',  to: 'snake#move',  as: nil
    post '/end',   to: 'snake#end',   as: nil
  end

  concerns :snake

  scope "/ml", default: { ml: true } do
    concerns :snake
  end

  resources :games, only: [:index, :show]
  resources :moves, only: [:show]
end

app/models/game.rb
require 'securerandom'

class Game
  attr_reader :id, :turn, :self_id, :board

  def initialize(id: nil, turn: 0, self_id:, board:)
    @id = id || SecureRandom.hex
    @turn = turn
    @self_id = self_id
    @board = board
  end

  def self.from_json(data)
    new(
      id: data['game']['id'],
      turn: data['turn'],
      self_id: data['you']['id'],
      board: Board.from_json(data['board'])
    )
  end

  def initialize_copy(other)
    @board = @board.dup
    @player = nil
    @enemies = nil
  end

  def snakes
    @board.snakes
  end

  def player
    @player ||= snakes.detect { |s| s.id == @self_id }
  end

  def enemies
    @enemies ||= snakes - [player]
  end

  def simulate(actions)
    game = dup
    game.simulate!(actions)
    game
  end

  def simulate!(actions)
    board.simulate!(actions)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Storage::Game.order(id: :desc).page(params[:page])
  end

  def show
    @game = Storage::Game.find_by(external_id: params[:id])

    respond_to do |format|
      format.html
      format.json do
        render json: @game, include: :moves
      end
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<table class="table game-table" style="width: 100%">
  <thead>
    <tr>
      <th>id</th>
      <th>Result</th>
      <th>start time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr class="game">
        <td>
          <%= link_to game.external_id, game_path(game) %>
        </td>
        <td>
          <%= game.human_result %>
        </td>
        <td>
          <%= l game.created_at %>
        </td>
        <td>
          <%= link_to "show", game_path(game) %>
          <%= link_to "play.battlesnake.com", game.external_url %>
        </td>
      </div>
    <% end %>
  </tbody>
</table>

<%= paginate @games %>

app/views/games/show.html.erb
<dl>
  <dt>id</dt>
  <dd><%= @game.external_id %></dd>
  <dt>started at</dt>
  <dd><%= l @game.created_at %></dd>
  <dt>finished at</dt>
  <dd><%= l @game.moves.last.created_at %></dd>
  <dt>Result</dt>
  <dd><%= @game.human_result %></dd>
  <dt>Snake version</dt>
  <dd><%= version_link @game.snake_version %></dd>
</dl>

<%= link_to(image_tag(@game.gif_url), @game.external_url) %>

<table class="table moves-table">
  <thead>
    <tr>
      <th>Turn</th>
      <th>Choice</th>
      <th>Runtime</th>
      <th>Remaining snakes</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <% @game.moves.order(turn: :asc).each do |move| %>
      <tr class="move">
        <td>
          <%= link_to move.turn, move_url(move) %>
        </td>
        <td>
          <%= move.decision %>
        </td>
        <td>
          <%= number_with_precision(move.runtime * 1000, precision: 1) %> ms /
          <%= number_with_precision(move.remote_latency, precision: 1) %> ms
        </td>
        <td>
          <%= move.remaining_snakes %>
        </td>
        <td>
          <%= move.heuristic_score %>
        </td>
      </div>
    <% end %>
  </tbody>
</table>